name: Publish Python Package (PyPi)

on:
  release:
    types: [published, edited]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: "Install build dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: "Build the package"
        run: |
          python -m build

      - name: "Publish package distributions to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1