name: "Release"

on:
  release:
    types: [published, edited]

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "ZIP the library"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}"
          zip petkit_api.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: ${{ github.workspace }}/petkit_api.zip
